title: Site

columns:
  - width: 2/3
    sections:
    fields:
      siteDescription:
        label: Site Description
        type: textarea
        size: small


  - width: 1/3
    sections:
      # a list of subpages
      pages:
        type: pages
        headline: Subpages

      # a list of files
      files:
        type: files
        headline: Files